package co.edu.uniajc.cajero.model;
// Generated 7/04/2019 01:08:10 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name = "Cuenta")
public class Cuenta implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer idCuenta;
	@ManyToOne
	@JoinColumn(name="id_banco")
	private Banco id_banco;
	@ManyToOne
	@JoinColumn(name="id_estado")
	private Estado id_estado;
	@ManyToOne
	@JoinColumn(name="id_producto")
	private Producto id_producto;
	@ManyToOne
	@JoinColumn(name="id_usuario")
	private Usuario id_usuario;
	private String numero;
	private BigDecimal saldo;
	private String clave;
	//private Set detalles = new HashSet(0);
//	private Set tarjetas = new HashSet(0);

	public Cuenta() {
	}

	public Cuenta(Banco id_banco, Estado id_estado, Producto id_producto, Usuario id_usuario, String numero, BigDecimal saldo,
		String clave) {
				this.id_banco = id_banco;
				this.id_estado = id_estado;
				this.id_producto = id_producto;
				this.id_usuario = id_usuario;
				this.numero = numero;
				this.saldo = saldo;
			    this.clave = clave;
			//	this.detalles = detalles;
			//	this.tarjetas = tarjetas;
			}

	public Integer getIdCuenta() {
		return idCuenta;
	}

	public void setIdCuenta(Integer idCuenta) {
		this.idCuenta = idCuenta;
	}

	public Banco getId_banco() {
		return id_banco;
	}

	public void setId_banco(Banco id_banco) {
		this.id_banco = id_banco;
	}

	public Estado getId_estado() {
		return id_estado;
	}

	public void setId_estado(Estado id_estado) {
		this.id_estado = id_estado;
	}

	public Producto getId_producto() {
		return id_producto;
	}

	public void setId_producto(Producto id_producto) {
		this.id_producto = id_producto;
	}

	public Usuario getId_usuario() {
		return id_usuario;
	}

	public void setId_usuario(Usuario id_usuario) {
		this.id_usuario = id_usuario;
	}

	public String getNumero() {
		return numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public BigDecimal getSaldo() {
		return saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public String getClave() {
		return clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "Cuenta [idCuenta=" + idCuenta + ", id_banco=" + id_banco + ", id_estado=" + id_estado + ", id_producto="
				+ id_producto + ", id_usuario=" + id_usuario + ", numero=" + numero + ", saldo=" + saldo + ", clave="
				+ clave + "]";
	}



}
