package co.edu.uniajc.cajero.model;
// Generated 7/04/2019 01:08:10 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "Estado")
public class Estado implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer idEstado;
	private String descripcion;
//	private Set cuentas = new HashSet(0);
//	private Set tarjetas = new HashSet(0);

	public Estado() {
	}

	public Estado(String descripcion) {
		this.descripcion = descripcion;
	//	this.cuentas = cuentas;
	//	this.tarjetas = tarjetas;
	}

	public Integer getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(Integer idEstado) {
		this.idEstado = idEstado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

//	public Set getCuentas() {
//		return this.cuentas;
//	}

//	public void setCuentas(Set cuentas) {
	//	this.cuentas = cuentas;
//	}

	//public Set getTarjetas() {
	//	return this.tarjetas;
//	}

	//public void setTarjetas(Set tarjetas) {
	///	this.tarjetas = tarjetas;
	//}

}
