package co.edu.uniajc.cajero.model;
// Generated 7/04/2019 01:08:10 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado")
public class Estado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6899525427141686998L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer idEstado;
	private String descripcion;


	public Estado() {
	}

	public Estado(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(Integer idEstado) {
		this.idEstado = idEstado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Override
	public String toString() {
		return "Estado [id_Estado=" + idEstado + ", descripcion=" + descripcion + "]";
	}

}
