package co.edu.uniajc.cajero.model;
// Generated 7/04/2019 01:08:10 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(name = "Movimiento")
public class Movimiento implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer idMovimiento;
	private String descripcion;
//	private Set detalles = new HashSet(0);

	public Movimiento() {
	}

	public Movimiento(String descripcion) {
		this.descripcion = descripcion;
	//	this.detalles = detalles;
	}

	public Integer getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(Integer idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	//public Set getDetalles() {
	//	return this.detalles;
	//}

	//public void setDetalles(Set detalles) {
	//	this.detalles = detalles;
	//}

}
