package co.edu.uniajc.cajero.model;
// Generated 7/04/2019 01:08:10 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tarjeta generated by hbm2java
 */
@Entity
@Table(name = "Tarjeta")
public class Tarjeta implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer idTarjeta;
	@ManyToOne
	@JoinColumn(name="idCuenta")
	private Cuenta idcuenta;
	@ManyToOne
	@JoinColumn(name="idestado")
	private Estado idestado;
	
	private String numero;
	private Date validthru;
	private int indBlock;
	private String clave;
	private Date fecCreacion;
	//private Set detalles = new HashSet(0);

	public Tarjeta() {
	}

	public Tarjeta(Cuenta idcuenta, Estado idestado, String numero, Date validthru, int indBlock, String clave) {
		this.idcuenta = idcuenta;
		this.idestado = idestado;
		this.numero = numero;
		this.validthru = validthru;
		this.indBlock = indBlock;
		this.clave = clave;
	}

	//public Tarjeta(Cuenta cuenta, Estado estado, String numero, Date validthru, int indBlock, String clave,
	//		Date fecCreacion, Set detalles) {
	//	this.cuenta = cuenta;
	//	this.estado = estado;
	//	this.numero = numero;
	//	this.validthru = validthru;
	///	this.indBlock = indBlock;
	///	this.clave = clave;
	//	this.fecCreacion = fecCreacion;
	///	this.detalles = detalles;
	//}

	public Estado getIdestado() {
		return idestado;
	}

	public void setIdestado(Estado idestado) {
		this.idestado = idestado;
	}

	public Integer getIdTarjeta() {
		return this.idTarjeta;
	}

	public void setIdTarjeta(Integer idTarjeta) {
		this.idTarjeta = idTarjeta;
	}



	public Cuenta getIdcuenta() {
		return idcuenta;
	}

	public void setIdcuenta(Cuenta idcuenta) {
		this.idcuenta = idcuenta;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Date getValidthru() {
		return this.validthru;
	}

	public void setValidthru(Date validthru) {
		this.validthru = validthru;
	}

	public int getIndBlock() {
		return this.indBlock;
	}

	public void setIndBlock(int indBlock) {
		this.indBlock = indBlock;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

//	public Set getDetalles() {
//		return this.detalles;
//	}

//	public void setDetalles(Set detalles) {
//		this.detalles = detalles;
//	}

	@Override
	public String toString() {
		return "Tarjeta [idTarjeta=" + idTarjeta + ", idcuenta=" + idcuenta + ", idestado=" + idestado + ", numero="
				+ numero + ", validthru=" + validthru + ", indBlock=" + indBlock + ", clave=" + clave + ", fecCreacion="
				+ fecCreacion + "]";
	}
}
