package co.edu.uniajc.cajero.model;
// Generated 7/04/2019 01:08:10 PM by Hibernate Tools 5.2.12.Final


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoIdentificacion generated by hbm2java
 */
@Entity
@Table(name = "tipoIdentificacion")
public class TipoIdentificacion implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -6899525427141686998L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer idIdentificacion;
	private String descripcion;


	public TipoIdentificacion() {
	}

	public TipoIdentificacion(String descripcion) {
		this.descripcion = descripcion;

	}
	
	public TipoIdentificacion(int idIdentificacion) {
		this.idIdentificacion = idIdentificacion;

	}

	public Integer getIdIdentificacion() {
		return this.idIdentificacion;
	}

	public void setIdIdentificacion(Integer idIdentificacion) {
		this.idIdentificacion = idIdentificacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Override
	public String toString() {
		return "TipoIdentificacion [id_Identificacion=" + idIdentificacion + ", descripcion=" + descripcion + "]";
	}

}
