package co.edu.uniajc.cajero.model;
// Generated 7/04/2019 01:08:10 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transaccion generated by hbm2java
 */
@Entity
@Table(name = "Transaccion")
public class Transaccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id_Transaccion;
	@ManyToOne
	@JoinColumn(name="idCajero")
	private Cajero idcajero;
	private Date fec_Creacion;
	private int ind_Estado;
	private BigDecimal valor;
	//private Set detalles = new HashSet(0);

	public Transaccion() {
	}

	public Transaccion(Cajero idcajero, Date fec_Creacion, int ind_Estado) {
		this.idcajero = idcajero;
		this.fec_Creacion = fec_Creacion;
		this.ind_Estado = ind_Estado;
	}

//	public Transaccion(Cajero cajero, Date fecCreacion, int indEstado, BigDecimal valor, Set detalles) {
	//	this.cajero = cajero;
	//	this.fecCreacion = fecCreacion;
	//	this.indEstado = indEstado;
	//	this.valor = valor;
	//	this.detalles = detalles;
	//}

	public Integer getId_Transaccion() {
		return this.id_Transaccion;
	}

	public void setIdTransaccion(Integer id_Transaccion) {
		this.id_Transaccion = id_Transaccion;
	}


	public Cajero getIdcajero() {
		return idcajero;
	}

	public void setIdcajero(Cajero idcajero) {
		this.idcajero = idcajero;
	}

	public Date getFec_Creacion() {
		return this.fec_Creacion;
	}

	public void setFecCreacion(Date fec_Creacion) {
		this.fec_Creacion = fec_Creacion;
	}

	public int getIndEstado() {
		return this.ind_Estado;
	}

	public void setIndEstado(int ind_Estado) {
		this.ind_Estado = ind_Estado;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Override
	public String toString() {
		return "Transaccion [idTransaccion=" + id_Transaccion + ", idcajero=" + idcajero + ", fecCreacion=" + fec_Creacion
				+ ", indEstado=" + ind_Estado + ", valor=" + valor + "]";
	}


}
