package co.edu.uniajc.cajero.model;
// Generated 7/04/2019 01:08:10 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Transaccion generated by hbm2java
 */
@Entity
@Table(name = "Transaccion")
public class Transaccion implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer idTransaccion;
	private Cajero cajero;
	private Date fecCreacion;
	private int indEstado;
	private BigDecimal valor;
	//private Set detalles = new HashSet(0);

	public Transaccion() {
	}

	public Transaccion(Cajero cajero, Date fecCreacion, int indEstado) {
		this.cajero = cajero;
		this.fecCreacion = fecCreacion;
		this.indEstado = indEstado;
	}

//	public Transaccion(Cajero cajero, Date fecCreacion, int indEstado, BigDecimal valor, Set detalles) {
	//	this.cajero = cajero;
	//	this.fecCreacion = fecCreacion;
	//	this.indEstado = indEstado;
	//	this.valor = valor;
	//	this.detalles = detalles;
	//}

	public Integer getIdTransaccion() {
		return this.idTransaccion;
	}

	public void setIdTransaccion(Integer idTransaccion) {
		this.idTransaccion = idTransaccion;
	}

	public Cajero getCajero() {
		return this.cajero;
	}

	public void setCajero(Cajero cajero) {
		this.cajero = cajero;
	}

	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	public int getIndEstado() {
		return this.indEstado;
	}

	public void setIndEstado(int indEstado) {
		this.indEstado = indEstado;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	//public Set getDetalles() {
	//	return this.detalles;
	//}

	//public void setDetalles(Set detalles) {
	//	this.detalles = detalles;
	//}

}
